name: Updating_Docker_Image

on:
  push:
    branches:
    - main

jobs:
  run_linters:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Run Linters
        uses: actions-hub/stylelint@master
        env:
          INDENT_SPACES: 4
          PATTERN: "**/*.css"

  docker_pushing:
    name: Pushing Docker Image
    runs-on: ubuntu-latest
    needs: run_linters
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
    
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
        
        
    - name: Docker build
    
      run: |
        docker build . -t ipashkayounot/git_sync:latest
    
    
    - name: Docker Push
    
      run: |
        docker push ipashkayounot/git_sync:latest
        
    
    - name: Docker logout
    
      run: |
        docker logout
